name: "Create snapshot of points"
on:
  schedule:
    # - cron: "0,30 * * * *" # every 0th and 30th minute of an hour
    - cron: "*/5 * * * *" # every 5 minutes
    # - cron: "0 */12 * * *" # every 12 hours
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
env:
  solana_version: 1.18.18
jobs:
  points-snap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "20"
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: install global mocha
        run: |
          export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH"
          npm install -g mocha
          npm install -g ts-mocha
          npm install -g typescript
          npm install -g @project-serum/anchor
          ts-mocha -h
      - name: install essential
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config build-essential libudev-dev
      - name: install solana
        run: |
          sh -c "$(curl -sSfL https://release.anza.xyz/v${{ env.solana_version }}/install)"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
          export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH"
          solana --version
      - name: setup solana
        run: |
          export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH"
          solana --version
          solana-keygen new -o "$HOME/.config/solana/id.json" --no-passphrase --silent
      - name: snapshot
        run: |
          export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH"
          export ANCHOR_WALLET="/home/runner/.config/solana/id.json"
          npm install
          npm run snap
      - uses: actions/upload-artifact@v4
        with:
          name: eclipse-points-snapshot-${{ github.run_id }}
          path: |
            ./data/*.json
            ./data/*.bin
  deploy:
    needs: [points-snap]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v2
      - name: Download snapshot
        uses: actions/download-artifact@v4
        with:
          name: eclipse-points-snapshot-${{ github.run_id }}
          path: ./data/
        continue-on-error: true
      - name: Configure Git
        run: |
          git config --global user.email stats@invariant.app
          git config --global user.name invariantStats
          git config --global filter.lfs.smudge "git-lfs smudge --skip -- %f"
          git config --global filter.lfs.process "git-lfs filter-process --skip"
          git config --global filter.lfs.required false
          git config --global filter.lfs.skip true
      - name: Remove LFS
        run: |
          git lfs uninstall
          rm -f .gitattributes
      - name: Stage and commit changes
        run: |
          git add ./data/
          git commit -m "Snapshot of points done!"
          git push origin master --force --no-verify
      - uses: actions/setup-node@v2
        with:
          node-version: "20"
      - name: Deploy to Production
        uses: amondnet/vercel-action@v20
        id: deploy-vercel-production
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: "--prod"
          scope: ${{ secrets.VERCEL_ORG_ID }}
